### ISSUE TITLE
It didn't detect external SD Card in android lollipop (5.1).

### ISSUE THREAD

**Issue by abdullah432** [hendrawd/StorageUtil#2]
In lollipop this statement
`StorageUtil.getStorageDirectories(this)`
return` /storage/emulated/`. Which load internal memory file twice but didn't load external SD Card files. Please fix the issue.

Also:
final String[] folders = File.separator.split(path) is not spliting path.
![bug](https://user-images.githubusercontent.com/48089976/66718143-fa179580-edf9-11e9-8a2c-1b1f6a809d10.JPG)

That's why it return `/storage/emulated/` which lead to load internal memory file twice.

**Comment by abdullah432** [comment]
I'm wondering why not just do
```
final String path = Environment.getExternalStorageDirectory().getAbsolutePath();
finalAvailableDirectoriesSet.add(path);
```
Instead of doing all these steps.
```
String rawStorageId = "";
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                final String path = Environment.getExternalStorageDirectory().getAbsolutePath();
                final String[] folders = File.separator.split(path);
                final String lastSegment = folders[folders.length - 1];
                if (!TextUtils.isEmpty(lastSegment) && TextUtils.isDigitsOnly(lastSegment)) {
                    rawStorageId = lastSegment;
                }
            }
            // i.e: "/storage/emulated/storageId" where storageId is 0, 1, 2, ...
            if (TextUtils.isEmpty(rawStorageId)) {
                finalAvailableDirectoriesSet.add(RAW_EMULATED_STORAGE_TARGET);
            } else {
                finalAvailableDirectoriesSet.add(RAW_EMULATED_STORAGE_TARGET + File.separator + rawStorageId);
            }
```

**Comment by hendrawd** [comment]
@abdullah432 This library based on [an answer from stackoverflow](https://stackoverflow.com/a/18871043/3940133) and the initial solution also wrong when splitting the path. I fixed
```java
final String[] folders = File.separator.split(path);
```
to
```java
final String[] folders = path.split(File.separator);
```

I don't think that it will load the internal memory file twice though, because it is backed by set
```java
final Set<String> availableDirectoriesSet = new HashSet<>();
```
That will make the contents unique

**Comment by hendrawd** [comment]
Why not simply do
```java
final String path = Environment.getExternalStorageDirectory().getAbsolutePath();
finalAvailableDirectoriesSet.add(path);
```
?

Because starting from `Jelly Bean MR1` (Android 4.2), there is a feature called multi-user. It will change the emulated path from `/storage/emulated` to `/storage/emulated/storageId`, where `storageId` is 0, 1, 2, ...; depends on how many users on the device. 

As far as I remember, the content of `Environment.getExternalStorageDirectory().getAbsolutePath()` is different from `System.getenv("EMULATED_STORAGE_TARGET")` and CMIIW, I can't access the storage directly from `Environment.getExternalStorageDirectory().getAbsolutePath()`.

**Comment by hendrawd** [comment]
@abdullah432 Please check version 1.1.0 and let me know if it solves your problem. And if it's not, please provide more detail about the phone manufacturer and model, so I can help to track and solve it.

**Comment by hendrawd** [comment]
I'm closing this since there is no more comment about this issue
